application: application-id
version: 1
runtime: jruby

handlers:
- url: /remote_api/*
  login: admin
  servlet: com.google.apphosting.utils.remoteapi.RemoteApiServlet

- url: /contacts/*
  login: required

resource_files:
- exclude: /README
- exclude: /Rakefile
- exclude: /db/**
- exclude: /doc/**
- exclude: /bin/**
- exclude: /log/**
- exclude: /script/**
- exclude: /test/**
- exclude: /tmp/**

static_files:
 - include: /**/*.ico
   expiration: 365d
 - include: /**/*.gif
   expiration: 365d
 - include: /**/*.jpeg
   expiration: 365d
 - include: /**/*.jpg
   expiration: 365d
 - include: /**/*.png
   expiration: 365d
 - include: /**/*.js
   expiration: 365d
 - include: /**/*.css
   expiration: 365d
